"""added completed_at column

Revision ID: 121ff831ded3
Revises: 6b57fc578479
Create Date: 2025-01-22 17:33:10.134352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '121ff831ded3'
down_revision: Union[str, None] = '6b57fc578479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convert_mp4_task', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.drop_index('idx_convert_mp4_task_cleaned_updated_key', table_name='convert_mp4_task')
    op.create_index('idx_convert_mp4_task_cleaned_updated_key', 'convert_mp4_task', ['is_cleaned', 'completed_at', 'key'], unique=True)
    op.drop_column('convert_mp4_task', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convert_mp4_task', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text("timezone('utc'::text, CURRENT_TIMESTAMP)"), autoincrement=False, nullable=True))
    op.drop_index('idx_convert_mp4_task_cleaned_updated_key', table_name='convert_mp4_task')
    op.create_index('idx_convert_mp4_task_cleaned_updated_key', 'convert_mp4_task', ['is_cleaned', 'updated_at', 'key'], unique=True)
    op.drop_column('convert_mp4_task', 'completed_at')
    # ### end Alembic commands ###
