"""added started_ts column for convert to mp4

Revision ID: 6b57fc578479
Revises: 8e944ff8f33b
Create Date: 2025-01-19 22:10:35.880920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b57fc578479'
down_revision: Union[str, None] = '8e944ff8f33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('convert_mp4_task', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('convert_mp4_task', 'started_at')
    # ### end Alembic commands ###
